apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: app
type: Opaque
data:
  client-id: NjMzNjEyODE3MDktajhnZHRiMGgwNmhoOHFrM3NyMmNjcmk1MzQ2Nm9hNmsuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  client-secret: R09DU1BYLXc3RlZXV1ZMenJXY1RKckRCelJjc3MwVDlJSW4=
  cookie-secret: QjRqZWZNMUdmRnpGOHZNR0R1djZZZz09